config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # list all tasks
  get "tasks", to: "tasks#index"
  # Add a new task
  get "tasks/new", to: "tasks#new", as: :new
  post "tasks", to: "tasks#create"
  # details of one task
  get "tasks/:id", to: "tasks#show", as: :task
  # edit a task
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update"
  # delete a task
  delete "tasks/:id", to: "tasks#destroy", as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params['id'])
    if @task.completed
      @checkbox = "fas fa-check-square"
      @text = "This task have been completed"
    else
      @checkbox = "fas fa-square"
      @text = "This task havn't been completed yet"
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to(tasks_path)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://kit.fontawesome.com/17d8b96ff8.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit the task</h1>

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.input :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%=link_to task.title, task_path(task) %> . <%= link_to "Delete", delete_path(task.id), method: :delete, data: { confirm: "Are you sure?" } %></li>
  <% end %>
</ul>
<hr class="rounded">
<%= link_to "Add a new task", new_path %>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>
<hr class="rounded">
<%= link_to "Back to the list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<%= link_to "Edit task", edit_path %>
<div class="grey">
  <%= @task.details %>
</div>
<p><i class="<%= @checkbox %>"></i> <%= @text %></p>
<hr class="rounded">
<%= link_to 'Back to the list', tasks_path %>